version: "3.9.2"
services:
  web:
    build: .
    ports:
      - 8090:8090
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - MONGODB_CONNSTRING=mongodb+srv://david:TyuI1705$@cluster0.qqb9bkj.mongodb.net/?retryWrites=true&w=majority
    command: uvicorn provider_service.app:app --host 0.0.0.0 --port 8090 --reload
  provider-service:
    build: .
    volumes:
      - .:/app
    ports:
      - 8090:8090
    image: provider-service:fastapi
    container_name: fastapi_container_provider
    command: uvicorn provider_service.app:app --host 0.0.0.0 --port 8090 --reload
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - ./data-mongodb:/data/db
    environment:
      MONGO_INITDB_DATABASE: mydatabase
      MONGO_INITDB_ROOT_USERNAME: david
      MONGO_INITDB_ROOT_PASSWORD: TyuI1705$$
    hostname: mongodb
    container_name: mongo_db_provider
    ports:
      - 27018:27017


